### ISSUE TITLE
Question regarding Actions and their Dependencies

### ISSUE THREAD

**Issue by davidsharpbell** [pmjones/adr#40]
Hello @pmjones,

I am trying to understand the core aspects of ADR. I saw you left out the Front Controller which is fine, but I am confused about where Action dependencies should be created.

In your example, your Action classes make perfect sense except that by your logic it sounds as though the Action class itself would have no dependencies. Because each Blog Action has its own dependencies, would we not create some sort of Factory pattern to encompass all Blog Actions?

I hope that makes sense.

**Comment by pmjones** [comment]
Hi @jakzodiac --

Each Action class can definitely have dependencies; e.g., it would need a domain object to call on, so it could pass input to that domain service. So yes, you would likely need a Factory of some sort to create the Action instance.

That Factory need not encompass only Blog actions. Any dependency injection system that lets you create "new instance" objects (rather than only "shared service" objects) should be capable of handling all Actions.

Does that begin to help?

**Comment by jakzodiac** [comment]
Totally. Thanks for the quick reply. Love your work!

**Comment by pmjones** [comment]
Thanks for saying. :-)
