### ISSUE TITLE
Giving more reason to Actions and Responders

### ISSUE THREAD

**Issue by sweiguny** [pmjones/adr#47]
Hi pmjones,

in [this issue](https://github.com/pmjones/adr/issues/35) you said this:

> For my part, having worked with ADR for a while, it turns out that every Action ends up doing exactly the same thing: marshal input, call the domain with that input to get a result, pass that result to the responder. As such, the Action portion can be completely extracted, and all you need to do is specify an input callable, a domain callable, and a responder callable; that information can be specified very easily via the routing system.

I am facing the sampe "problem": (almost) empty Actions.
For me, your statement sounds like the **Action** could be entirely omitted.

_I'd like to explain why:_

De facto each Action has a Response. I think this is a core element of the pattern.
But not each action may have a Domain. E.g. you have only one welcome page, that does not even fetch the name from the database/session/anywhere but only sais "hi" (we all know, there are such pages out there).

So the Response is always needed, whether a Domain exists or not. And as the Action only forwards incoming parameters to the Response or forwards data from the Domain to the Response, why the Response should not marshal its data itself?
I think this would be better than having a lot of (almost) empty Actions.
But well, it would not seperate concerns in a sensible way.

Hence I am looking for a "killer argument" to not let the Responder gather its data.
I am curous what you have to say :)

best regards

**Comment by pmjones** [comment]
> For me, your statement sounds like the Action could be entirely omitted.

I can see why you would think that. To be (I hope) more clear: I'm not saying to omit the Action. I'm saying that there can be a single Action class for the entire system, and when you instantiate it, you can pass it an input callable, a domain callable, and a responder callable. That's what Arbiter does for Radar: https://github.com/arbiterphp/Arbiter.Arbiter/blob/1.x/src/ActionHandler.php#L61-L81 (the "Action" there is just a Value Object that carries the callables.)

Or you can write your own generalized Action handler to use interfaces instead of callables.

FWIW, Arbiter handles the situation of there being *only* a responder, or there being a domain but no needed input.

> I am looking for a "killer argument" to not let the Responder gather its data.

Ah, I wish I had a killer argument for *something* in my life, a bulletproof unbeatable reason for anything at all. :-)

But I don't have one. The best I can tell you is that, if the Responder is responsible for marshalling input, *and* calling the domain, *and* doing all the presentation work, then you're kind of back at the Page Controller pattern, or even the old Sun Model 2 "MVC" that ADR attempts to move away from. That seems like a bit too much responsibility for me.  The benefit of ADR is that those three things are separated.

Does that begin to make a little sense? I'm happy to talk more about it, or address more specific elements of your questions.

**Comment by sweiguny** [comment]
thank you for your reply!

> I'm saying that there can be a single Action class for the entire system

in fact, i was thinking about doing that in my project. but that seems to be a bit understated...
hm... i will give it some more thought.

> Ah, I wish I had a killer argument for something in my life, a bulletproof unbeatable reason for anything at all. :-)

Well, i think there are many killer arguments for many things in life, but that is another story :-)

But i get your point. i am aware, that the Responder would have too much responsibility then.
I am only wondering how to give the Action a little bit more purpose than only beeing an entry point.
In my case almost all Actions consist only of the class definition, because they inherit most of the logic from the base class (AbstractAction).

The Responder faces the same problem as well, because most logic (setting HTTP headers, ..., ???) is implement in the base class (AbstractResponder). In my case the Responders are fairly empty, too, because they only forward data to the views.

The only places where the real work is done is in the Domain and in the View.

And it seems wrong to me to combine the Responder and the View. But what do you think about that?

**Note**: In my case a View is an object, which contains Widget objects which actually generate the html code. The widgets provide an interface that helps generating html code.

**Comment by pmjones** [comment]
Hi @sweiguny --

> The only places where the real work is done is in the Domain and in the View.

I think that's an accurate assessment. Further, I think that's probably the "right thing." Those are the only places where anything interesting is happening.

> And it seems wrong to me to combine the Responder and the View.

I can see why you'd say that. But! ;-)

I take it that when you say View, you mean the templating system that generates the HTML. (That's what most people I talk to mean, anyway.) I have come to understand the "View" to be more than just the HTML (or JSON, or whatever). In a request/response environment, the "View" is *the entirety of the response* -- not just the HTML in the body of the response, but also all the headers. That's why the Responder is tasked with dealing with headers *and* with the body of the response. 

So, [the template is not the view](http://paul-m-jones.com/archives/5993) -- the *response* is the view, and the Responder is what builds it.

Does that make sense?

**Comment by sweiguny** [comment]
> Does that make sense?

hm.. I don't really know.
As you say, a View is the templating system that generates the HTML. Not more and not less.
For me a Responder would use a View to generate the "body" in case it must return HTML. In case of an AJAX-Request, it may have to return JSON-Data, so it doesn't use the View.

Does _that_ make sense? :)

**Comment by pmjones** [comment]
> As you say, a View is the templating system that generates the HTML. Not more and not less.

Almost! The View in a request/response system generates *the whole response*, including the status line, all the headers (including cookies), and the body. The template system is part of that, but not all of it.
