### ISSUE TITLE
Validation to happen in the domain, where?

### ISSUE THREAD

**Issue by notflip** [pmjones/adr#63]
I'm reading through the documentation, and I'm very interested! This makes so much more sense then MVC

Regarding the part where it says

> "all forms of input validation, error handling, and so on, are therefore pushed out of the Action and into the Domain"

Where in the domain would that happen? Is it good practice to put the validation logic in the Service? In the Repository (seems unlikely)? Or do you create another layer? Thank you

**Comment by pmjones** [comment]
Hey there! I thought I had this as part of the "Implementation" notes, but I guess not. Here's a paraphrase of my opinion as presented at https://www.reddit.com/r/PHPhelp/comments/iebld4/in_domain_driven_development_would_the_controller/g2gwvmq/ :

The earliest place where validation should occur is the Service; that is, the outermost element of the Domain. That might be a Transaction Script, Service Layer, Application Service, Use Case, etc.

You may choose to do the validation work directly in that Service, but for several reasons, it might be better to encapsulate the validation logic in its own class. You can then inject that into any Service as needed. Alternatively, you may find other reasons to push validation further down into the Domain, whether in the Domain Services, the Aggregates, or the Entities.

Finally, I would say that any validation errors from the Domain should be captured by the outermost Service, encapsulated into Domain Payload objects, and then those Domain Payload objects should be returned to the calling code. Do that instead of emitting Exceptions from the Domain into the User Interface layer.

Hope that all made sense!

**Comment by notflip** [comment]
Thanks for the explanation Paul! It does make sense as I read it, I might have to reread it a few times while implementing! Are those terms, such as Domain Payload, Domain Service, Application Service, and others related to DDD?

**Comment by pmjones** [comment]
Yes, those are all DDD terms (or other related terms). You can read about some of them here:

http://paul-m-jones.com/post/2014/09/30/action-domain-responder-and-the-domain-payload-pattern/

That's an older article, but I think you will get the point.

Strictly speaking, DDD is not required for ADR, it's just that they make a good match. As long as you keep a good separation between your User Interface code and your Domain code, you'll be all right. :-)
